export enum SocialPlatform {
  instagram = "instagram",
  facebook = "facebook",
  pinterest = "pinterest",
  github = "github",
  reddit = "reddit",
  steam = "steam",
  twitch = "twitch",
  medium = "medium",
  minecraft = "minecraft",
  patreon = "patreon",
  etsy = "etsy",
  soundcloud = "soundcloud",
  linktree = "linktree",
  "9gag" = "9gag",
  "ask.fm" = "ask.fm",
  dockerhub = "dockerhub",
  tumblr = "tumblr",
  wikipedia = "wikipedia",
  "dev.to" = "dev.to",
  shopify = "shopify",
  snapchat = "snapchat",
  vimeo = "vimeo",
  behence = "behence",
  dribbble = "dribbble",
}
